# Generated by Django 3.2.25 on 2024-11-12 12:08

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('url', models.SlugField()),
                ('tcreate', models.DateTimeField(auto_now_add=True)),
                ('tstart', models.DateTimeField(null=True)),
                ('tfinish', models.DateTimeField(null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('approxtime', models.IntegerField()),
                ('condit', models.CharField(max_length=2)),
                ('priority', models.IntegerField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('uptasks', models.TextField()),
                ('subtasks', models.TextField()),
                ('collapse', models.CharField(default='y', max_length=2)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField()),
                ('title', models.CharField(max_length=2000)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(max_length=2000)),
                ('tstart', models.DateTimeField(null=True)),
                ('tstop', models.DateTimeField(null=True)),
                ('waistedtime', models.IntegerField(default=0)),
                ('public', models.CharField(default='u', max_length=2)),
                ('typ', models.CharField(default='u', max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myblog.task')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstart', models.DateTimeField(null=True)),
                ('tfinish', models.DateTimeField(null=True)),
                ('public', models.CharField(default='u', max_length=2)),
                ('typ', models.CharField(default='u', max_length=2)),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.task')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
